### ISSUE TITLE
Linux -install support

### ISSUE THREAD

**Issue by FiloSottile** [FiloSottile/yubikey-agent#10]
On Linux, running `yubikey-agent -install` should create, install, and start a local user systemd unit, and show the environment variable the user needs to set (where the socket is in a relevant stable path in the home).

**Comment by chlunde** [comment]
FYI, this seems to work on Fedora 32, but there's a few things I think should be considered:
* UID in socket path
* Socket activation
* `pcscd` dependency?

### Unit `.config/systemd/user/yubikey-agent.service`
```ini
[Unit]
Description=yubikey-agent is a seamless ssh-agent for YubiKeys

[Service]
ExecStart=%h/go/bin/yubikey-agent -l /var/run/user/%U/yubikey-agent.sock

[Install]
WantedBy=default.target
```
### Commands to execute (without sudo)
```bash
systemctl --user daemon-reload
systemctl --user enable yubikey-agent
systemctl --user start yubikey-agent
```

**Comment by unchainedio** [comment]
What do i need to do to have yubikey-agent used when i ssh?  i installed via AUR, i setup ssh key on my remote server and added the authentication token to yubikey 5c.

im unclear on further configuration needed?

**Comment by FiloSottile** [comment]
Thinking more about this, I'd rather have packages and manual instructions than an `-install` command.
