### ISSUE TITLE
Yubico Authenticator not Working any more

### ISSUE THREAD

**Issue by fishooo0815** [FiloSottile/yubikey-agent#109]
I installed the yubikey-agent
It is working fine with SSH.

But the Yubico Authenticator can't find the Key any more:

<img width="269" alt="Screenshot 2021-11-29 at 17 17 54" src="https://user-images.githubusercontent.com/92112492/143903836-af1dda89-bdc2-45db-888f-6ae5edd69262.png">

**Comment by fishooo0815** [comment]
Hi, since i am totaly new to GitHub, i am also open to Tipps, how to create an issue post in a good way.

**Comment by fishooo0815** [comment]
Maybe there is an workaround for this issue. Something like a switch for turning the yubikey-agent on and off, for the time it is conflicting with the Yubikey Authenticator Application.

**Comment by philandstuff** [comment]
This is a limitation of the hardware. You can send a SIGHUP to yubikey-agent to disconnect the connection so that yubico-Authenticator can connect.

**Comment by philandstuff** [comment]
Something like `pkill -HUP yubikey-agent` should do the job. Yubikey-agent will disconnect but keep running.

**Comment by fishooo0815** [comment]
And is there a way to reconnect this?

**Comment by philandstuff** [comment]
yes, the next ssh operation will reconnect. it may ask for your passphrase/PIN again at that point.

**Comment by fishooo0815** [comment]
Is it posible to trigger the command `pkill -HUP yubikey-agent`...
... after the connection is asstabliched
... or after a amound of secconds?

Maybe placed in the `~/.ssh/config` file?
