### ISSUE TITLE
Pinentry prompt does not show up

### ISSUE THREAD

**Issue by YugiFanGX** [FiloSottile/yubikey-agent#134]
Kali latest rolling release gives the following error message:

agent 13: pin prompt: unexpected response: ERR 83918950 Inappropriate ioctl for device <Pinentry>

**Comment by YugiFanGX** [comment]
Occurs on KDE Plasma. No issues found on xfce

**Comment by jhwarner** [comment]
If you're still having this problem, I was able to fix it on KDE by adding:

`pinentry-program /usr/bin/pinentry-qt`

To `~/.gnupg/gpg-agent.conf`

This is on Arch Linux and KDE Wayland.
