### ISSUE TITLE
ssh fails to connect to agent

### ISSUE THREAD

**Issue by zachgersh** [FiloSottile/yubikey-agent#16]
There seems to be something slightly strange going on for me on my mac:

if I run the agent directly myself (in the foreground) I can connect to the `AUTH_SOCK` and everything is fine.

On the other hand, if I attempt to let `brew services` start the agent (which I believe is root) my user can not longer access the agent `AUTH_SOCK`, I basically just get permission denied.

Do I have my mac set up in some strange way?

**Comment by zachgersh** [comment]
so trying:

```
sudo brew services stop yubikey-agent
brew services start yubikey-agent
```

No agent is running on the machine. Before, the agent was just running as root when I would `sudo ps ax`

**Comment by zachgersh** [comment]
alright - to fix this bit, I had to make sure that I `chown`'ed over the log file for the `yubikey-agent` in `/usr/local/var/log`. I figured this out by looking at `launchctl list` and noticing that the status for `yubikey-agent` was 78 aka some problem has occurred starting.

**Comment by charlesfracchia** [comment]
> alright - to fix this bit, I had to make sure that I `chown`'ed over the log file for the `yubikey-agent` in `/usr/local/var/log`. I figured this out by looking at `launchctl list` and noticing that the status for `yubikey-agent` was 78 aka some problem has occurred starting.

Thank you so much for this answer. I was going crazy running down this exact same rabbit hole. I had `chown`ed every other file but this one...
