### ISSUE TITLE
Setup should print existing public key

### ISSUE THREAD

**Issue by onurguzel** [FiloSottile/yubikey-agent#18]
I am using PIV authentication for logging in to my computer and don't want to delete existing keys.

Setup should print the existing public key and then offer the flag to reset and start fresh. I can try to implement and create a PR if you accept this feature.

**Comment by FiloSottile** [comment]
Existing keys are not officially supported, but if your manual setup is close enough to the `-setup` one, you can use `ssh-add -L` to see the public key.

https://github.com/FiloSottile/yubikey-agent/blob/master/README.md#manual-setup-and-technical-details
