### ISSUE TITLE
Get Homebrew not to show "sudo" in the brew services command

### ISSUE THREAD

**Issue by FiloSottile** [FiloSottile/yubikey-agent#25]
yubikey-agent should not be run as root, but Homebrew autocatically shows `sudo brew services start`, causing issues like #16.

**Comment by bac** [comment]
Until you can solve this problem a note in the documentation would go a long way. I just ran into #16 and would've been stuck without the solution presented in it.

**Comment by FiloSottile** [comment]
Good idea, added a comment to the comment at the top of the docs.
