### ISSUE TITLE
ssh config example has order reversed

### ISSUE THREAD

**Issue by bac** [FiloSottile/yubikey-agent#28]
In the README you have the following snippet to show how to use yubikey-agent for all hosts but one:

```
Host *
    IdentityAgent /usr/local/var/run/yubikey-agent.sock

Host example.com
    IdentityAgent $SSH_AUTH_SOCK
```

SSH will apply the first match so the order here needs to be reversed.  As written example.com will attempt to use yubikey-agent.

**Comment by FiloSottile** [comment]
Oh good catch!
