### ISSUE TITLE
Service won't start after macOS update

### ISSUE THREAD

**Issue by DrJosh9000** [FiloSottile/yubikey-agent#30]
I have version 0.1.1 installed with Homebrew. I noticed that yubikey-agent stopped working. From `/usr/local/var/log/yubikey-agent.log`:

```
Failed to listen on UNIX socket: listen unix /usr/local/var/run/yubikey-agent.sock: bind: no such file or directory
```

(Side note: lack of timestamps in the log is mildly annoying.)

Seemingly the `run` directory disappeared from `/usr/local/var/`, and the only thing I can think of is today's macOS update to 10.15.5, which might have nuked it (or perhaps the reboot?). Recreating the directory brought the service back to life.

Should yubikey-agent ensure this directory exists (instead of the Homebrew script)?

**Comment by fiadliel** [comment]
The same happened to me; and now you mention it, it was after a MacOS patch update.
