### ISSUE TITLE
Cant find yubikey-agent.sock

### ISSUE THREAD

**Issue by unchainedio** [FiloSottile/yubikey-agent#31]
I had everything working fine and then i woke up after an update of some SW on Manjaro and i can no longer find the yubikey-agent.sock

How do i know where to find this file on arch/manjaro?  

i had this in my zshell .zshrc, it used to work yesterday 

export SSH_AUTH_SOCK="/var/run/user/1000/yubikey-agent/yubikey-agent.sock"  

and then today i can no longer find this flie after some system updates.

How do i get this file and where do i place it?

i uninstalled and reinstalled yubikey-agent and i still cant find this file.

**Comment by exussum12** [comment]
When you run yubikey-agent you specify where this is

-l /var/run/yubikey-agent/yubikey-agent.sock

Assuming thats in your init system, check to see if yunikey agent is running (ps aux | grep yubikey-agent) if it is you should see the path on the screen.

**Comment by unchainedio** [comment]
i dont see any locatoin for it.  Here is what i get from that 

ps aux | grep yubikey-agent

unchain+  222778  0.0  0.0   6300  2348 pts/1    S+   16:40   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox yubikey-agent


Any help would be appreciated

**Comment by exussum12** [comment]
Doesnt look like yubikey-agent running, thats just the line for your grep. 

Check the systemd logs (assuming its been set up with systemd ?)

**Comment by unchainedio** [comment]
i installed this through AUR.  i dont see any instructions for linux.  Is there a Linux install instruction i havent seen?

**Comment by exussum12** [comment]
systemctl start yubikey-agent.service 
systemctl enable yubikey-agent.service should start it and then auto start on next boot too

**Comment by unchainedio** [comment]
thanks, i got it (yubikey-agent) working but u2f is not working now.  i try and login to u2f services and the system is not recognizing the yubikey


unchain+  251682  0.0  0.0 1151180 6348 ?        Ssl  05:29   0:00 /usr/bin/yubikey-agent -l /run/user/1000/yubikey-agent/yubikey-agent.sock
unchain+  253129  0.0  0.0   6300  2168 pts/1    S+   05:37   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox yubikey-agent

**Comment by exussum12** [comment]
I can't replicate that, As the README says my yubikey authenticator doesnt work, but twitter github and AWS all accept my key no problem while yubikey-agent is active

**Comment by unchainedio** [comment]
if i plug in these udev rules 

https://support.yubico.com/support/solutions/articles/15000006449-using-your-u2f-yubikey-with-linux

would it mess anything up with yubikey-agent?

**Comment by exussum12** [comment]
the udev rules are part of ubuntu, so my system is using them, and I have no issue with u2f and yubikey-agent, so I assume not

**Comment by unchainedio** [comment]
adding udev rules from yubico worked.  thanks seems to work fine now.
