### ISSUE TITLE
yubikey-agent service inactive (dead)

### ISSUE THREAD

**Issue by r1cebank** [FiloSottile/yubikey-agent#39]
Hi I installed this package using the AUR package and ran the following:

```
systemctl daemon-reload --user
sudo systemctl enable --now pcscd.socket
systemctl --user enable --now yubikey-agent
```
But then I realize, when the computer is rebooted, the yubikey-agent do not restart, this cause the SSH_AUTH_SOCK to not be found.

Here is the output for `systemctl --user status yubikey-agent`
```
● yubikey-agent.service - Seamless ssh-agent for YubiKeys
     Loaded: loaded (/usr/lib/systemd/user/yubikey-agent.service; enabled; vend>
     Active: inactive (dead)
       Docs: https://filippo.io/yubikey-agent
```

System information:

```
OS: Manjaro 20.0.3 Lysia
Kernel: x86_64 Linux 5.6.16-1-MANJARO
DE: GNOME 3.36.3
```

Anyhelp would be nice, thank you

**Comment by r1cebank** [comment]
I tried some solutions regarding the inactive user service, it appears if I change the target to default instead of multi-user it fixes the issue. I am wondering if this is a known issue or just how my system is. If the fix can be included in the AUR package that would be great. 

https://bbs.archlinux.org/viewtopic.php?id=170344

**Comment by LeSuisse** [comment]
I confirm the issue when you start with a local GUI login.

Setting `WantedBy` to `default.target` is indeed better as it will be (most of the time) an alias of `multi-user.target` or `graphical.target` depending on the situation.

I updated the AUR package (0.1.3-2) with the change. Note that you will to recreate the appropriate symlink with `systemctl --user enable yubikey-agent`.

**Comment by FiloSottile** [comment]
Thank you @LeSuisse!

**Comment by r1cebank** [comment]
Thanks @LeSuisse
