### ISSUE TITLE
Use sockets passed in from systemd

### ISSUE THREAD

**Issue by flokli** [FiloSottile/yubikey-agent#44]
This would allow yubikey-agent to be started socket-activated by systemd.
Background: https://vincent.bernat.ch/en/blog/2018-systemd-golang-socket-activation

**Comment by tv42** [comment]
Exiting on idle and letting socket activation restart the service would make https://github.com/FiloSottile/yubikey-agent/issues/4 slightly less likely to bother me, too.

Yes, that would forget the PIN when idle, but that might even be desirable...

Not sure if there's (still) a race between shutting down and getting new connections, AFAIK that was not easy to handle right some 5 years back.

**Comment by FiloSottile** [comment]
I would take a PR for this, but can't implement it myself as I don't regularly use Linux desktop environments.
