### ISSUE TITLE
use notification library instead of shelling out to notify-send

### ISSUE THREAD

**Issue by flokli** [FiloSottile/yubikey-agent#45]
`main.go` currently shells out to `osascript` or `notify-send` when sending a notification:

https://github.com/FiloSottile/yubikey-agent/blob/master/main.go#L337-L339

It doesn't implement any notification logic for other platforms.

"https://github.com/gen2brain/beeep provides a cross-platform library for sending desktop notifications, alerts and beeps".

It doesn't rely on `notify-send` being in `$PATH` (only as a fallback, tries via dbus first), and in addition to Darwin, it also supports sending notifications on Windows.

**Comment by FiloSottile** [comment]
github.com/gen2brain/beeep is a very large dependency tree for a tangential feature such as the notifications. I think we'll take the tradeoff here.
