### ISSUE TITLE
pin-policy set to always?

### ISSUE THREAD

**Issue by teancom** [FiloSottile/yubikey-agent#48]
I have reset my old YubiKey 4 that I had lying around using both `yubikey-agent -setup` as well as `ykman piv reset`, and in both cases it prompts me for the PIN every single time, instead of once per session (which is what I expected to happen, based on the README). Is there a configuration option I'm missing?

**Comment by drod3763** [comment]
I have the same issue.

**Comment by smlx** [comment]
This is probably https://github.com/go-piv/piv-go/issues/60

What firmware version do you have on the keys that don't work?

**Comment by FiloSottile** [comment]
It looks like this is indeed the linked upstream issue. If you could pop in there and report your firmware version and whether it supports PIN caching, that would be great.
