### ISSUE TITLE
contributed systemd unit doesn't work in user session

### ISSUE THREAD

**Issue by terinjokes** [FiloSottile/yubikey-agent#49]
The systemd unit at [/contrib/systemd/user/yubikey-agent.service](https://github.com/FiloSottile/yubikey-agent/blob/4e85c15e0331e3e4c43c7707baa32646d01e5450/contrib/systemd/user/yubikey-agent.service) implies that it is suitable for the user systemd daemon, however it contains options that required privileges to run, resulting in errors similar to the following:

```
systemd[28428]: yubikey-agent.service: Failed to set up mount namespacing: Operation not supported
systemd[28428]: yubikey-agent.service: Failed at step NAMESPACE spawning /usr/bin/yubikey-agent: Operation not supported
```

This is reflected in similar issues upsteam, such as https://github.com/systemd/systemd/issues/9870. I can try paring the list down to options that work.

**Comment by philandstuff** [comment]
As a datapoint, I have the provided unit file running unmodified (other than executable path) on my machine as a user service. 

I believe the capability to use particular options is distro-specific; I’m running on nixos. Indeed the systemd issue you linked says

> OTOH that aspect cna change depending on all sorts of configuration, so I’m not sure how this could be documented in a way that makes sense...

I’m not sure the right solution here. I guess we want distributions to package a unit that uses at many of the given options that work, but ultimately it’s the packager’s job to make it work.

**Comment by terinjokes** [comment]
For what it's worth, I'm on NixOS 20.03.

**Comment by philandstuff** [comment]
Huh. Well i recently packaged yubikey-agent for NixOS unstable so I’m unsure what might have changed in the meantime.

**Comment by terinjokes** [comment]
I'm unsure. Do you have a different kernel (5.4.58) or systemd (243.7)? I'm happy to move NixOS conversation elsewhere.

**Comment by terinjokes** [comment]
It looks like this requires https://github.com/systemd/systemd/commit/5749f855a76bedba942768b82cfc15a440b8e064 which is in systemd v245. Let me see about fetching this from unstable.

**Comment by terinjokes** [comment]
Can confirm, using 245.6 from unstable results in the unmodified unit file working. Looking at [Repology](https://repology.org/project/systemd/versions), it looks like this version is available on most of the common desktop distributions I'm aware of (backports on Debian Stable, Ubuntu 20.04 LTS, Fedora 32). Biggest outliers look to be NixOS 20.03 and Raspian Stable.
