### ISSUE TITLE
Data object or application not found

### ISSUE THREAD

**Issue by kfken** [FiloSottile/yubikey-agent#5]
Running on Ubuntu 20.04, when trying to login, I get:

agent 11: could not get public key: command failed: smart card error 6a82: data object or application not found

I have private keys loaded on my Yubikey 5 that I created via gpg.  I have SSH_AUTH_SOCK set and I installed libpcsclite-dev per piv-go instructions.  I also killed gpg-agent.  Any ideas what might be going on?  I

**Comment by kfken** [comment]
Hmm, actually it seems that gpg does not write the keys to the PIV slots.  So it looks like I'm limited to RSA 2048 key for SSH in the PIV slot.  

I'll go back and generate a key and reopen if I still have a problem.

**Comment by FiloSottile** [comment]
There will be a `yubikey-agent setup` command before this is done which will do it for you, by the way!
