### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by philandstuff** [FiloSottile/yubikey-agent#59]
0.1.3 was released in June, and there's been [some development since then](https://github.com/FiloSottile/yubikey-agent/compare/v0.1.3...master). I'm particularly interested in #46.  Can a new release be cut please?

**Comment by philandstuff** [comment]
Please please can we get a new release?  I've cut a [new package PR on nixpkgs](https://github.com/NixOS/nixpkgs/pull/119632) pointing at main, but not having a tag means packagers have to jump through extra hoops (in this case, I have to mark the package with an `unstable-2021-xx-xx` version number).  It would be easier to have a tag to point to, to demonstrate to other packagers that I'm using a good commit.

**Comment by n0nvme** [comment]
Hey, @FiloSottile, maybe you should transfer ownership of the repo to the community that interested in maintaining and releasing new features for this project?

**Comment by FiloSottile** [comment]
Tagged v0.1.4.

I try to make projects that require little maintenance to be useful, and work on them in bursts/cycles to make significant changes when their time comes. I expect the next round of yubikey-agent will be about adding the option to add keys with custom policies, and age support.
