### ISSUE TITLE
UX/Roadmap question: importing existing keys

### ISSUE THREAD

**Issue by jstasiak** [FiloSottile/yubikey-agent#65]
Hey, thanks a lot for creating this project!

One question comes to my mind: is it possible to import existing SSH keys to a Yubikey (using any mechanism, not necessarily yubikey-agent itself) so that yubikey-agent can use them just like the keys it created on the device? Assuming it's not possible right now and it's just something that's not implemented in yubikey-agent – is it likely to exist in the future? Are pull requests implementing it welcome?

My use case is to generate a key on a trusted secure machine (temporary, disposable and clean system, no network etc.), upload it to a Yubikey and also store an encrypted copy on a usb-stick for extra safety in case my Yubikey stops working at some point. (Having multiple Yubikeys with different SSH keys on each of them is not suitable for me.)

**Comment by FiloSottile** [comment]
I understand the use case, but it's an advanced scenario that we will not support in `-setup`. We might allow using such a key once it's been generated with some other tool. See #91 for that.
