### ISSUE TITLE
Can't use pin cached in the system keystore (libsecret)

### ISSUE THREAD

**Issue by ava1ar** [FiloSottile/yubikey-agent#73]
Using latest version from git on Arch with Yubikey 5 Nano and trying to cache the PIN to the system keystore. Saving the pin to the store works and I see it there, however agent fails to read/use the value from the store.

When trying to ssh to the host (after service restart, so pin entry is required), I am getting the following error message:

```
sign_and_send_pubkey: signing failed for ECDSA "YubiKey #XXXXXXXX PIV Slot 9a" from agent: agent refused operation
```

In the service log I see the following:

```
Jan 09 17:45:38 pan-cf-sv9 yubikey-agent[4814]: 2021/01/09 17:45:38 agent 13: pin prompt: unexpected response: S PASSWORD_FROM_CACHE
```

Does it suppose to work? Am I doing something wrong here?

**Comment by ava1ar** [comment]
Looks like the issue is addressed in https://github.com/gopasspw/gopass/pull/1641 for gopass. You either need to wait for the next release or just use recent commit for gopass module dependency

**Comment by FiloSottile** [comment]
The fix made its way into the github.com/gopasspw/pinentry version we use.
