### ISSUE TITLE
Yubikey Agent failing to load Manjaro  (Namespace Spawn Error)

### ISSUE THREAD

**Issue by unchainedio** [FiloSottile/yubikey-agent#77]
I am on Manjaro Linux Kernel 5.10.13-2, yubikey agent is failing to load..

![alt image](https://i.imgur.com/HzCqOZn.png)

**Comment by FiloSottile** [comment]
It looks like user namespaces are somehow not supported on your system. You can try removing the RestrictNamespace line from the unit file.

https://github.com/FiloSottile/yubikey-agent/blob/4998d8c3d76cbfa97fd1af2953d8eea36ae290e8/contrib/systemd/user/yubikey-agent.service#L10

Please feel free to report back for other users that might encounter the same issue, closing as this looks like an issue between systemd and your OS, not something we can fix in yubikey-agent.

**Comment by unchainedio** [comment]
where does yubikey-agent look for this service file on arch?  i dont see it in /etc/systemd/user

**Comment by unchainedio** [comment]
I have reverted back to my image before i upgraded my kernel...

with kernel 5.10.1  yubikey-agent works fine.  when i upgrade to 5.10.13-2 it doesnt work.

This appears to be an issue with the new kernel compatibility...

**Comment by FiloSottile** [comment]
That's probably useful debugging information to bring to the owner of the package in your distribution. The service file is managed by systemd, not by yubikey-agent. All this happens before yubikey-agent has the opportunity to start.
