### ISSUE TITLE
[manjaro/gnome] service doesnt start properly at boot, fails to promt for device pin

### ISSUE THREAD

**Issue by MaxRink** [FiloSottile/yubikey-agent#87]
I always need to restart yubikeyagent service after booting my system, as the pin promt fails otherwise.
After restarting i get the correct promt in my gnome session

**Comment by FiloSottile** [comment]
This sounds like an issue with pinentry not knowing what the graphical session is. I'm afraid I can't help debug this further but gpg-agent might have had similar issues so you might be able to find debugging info there.
