### ISSUE TITLE
Not working on Ubuntu 21.04

### ISSUE THREAD

**Issue by nidkil** [FiloSottile/yubikey-agent#88]
Hi,

I'm trying to get yubikey-agent working on Ubuntu server 21.04 amd64. I have installed ykman and followed the systemd instructions. yubikey-agent is working, as I can initialize the key. The systemd service is running. When I call ssh it doesn't seem like it is going through yubikey-agent.

Is there away to debug yubikey-agent?

**Comment by FiloSottile** [comment]
You might have not set SSH_AUTH_SOCK.
